abc:
  adapter:
    module: biocypher_metta.adapters.abc_adapter
    cls: ABCAdapter
    args:
      filepath: ./samples/hsa/abc.forgedb_sample.csv.gz
      label: activity_by_contact
      hgnc_to_ensembl_map: ./aux_files/hgnc_to_ensembl.pkl
      tissue_to_ontology_id_map: ./aux_files/abc_tissues_to_ontology_map.pkl
      dbsnp_rsid_map: None
  outdir: abc
  nodes: false
  edges: true
